//
//  WeatherDetailsRouter.swift
//  MirianMaglakelidze#28
//
//  Created by Admin on 8/31/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol WeatherDetailsRoutingLogic {
//    func routeToWeatherForecast(segue: UIStoryboardSegue?)
}

protocol WeatherDetailsDataPassing {
    var dataStore: WeatherDetailsDataStore? { get }
}

class WeatherDetailsRouter: NSObject, WeatherDetailsRoutingLogic, WeatherDetailsDataPassing {
    
    weak var viewController: WeatherDetailsViewController?
    var dataStore: WeatherDetailsDataStore?
    
    // MARK: Routing
//    func routeToWeatherForecast(segue: UIStoryboardSegue?) {
//        let storyboard = UIStoryboard(name: "Main", bundle: nil)
//        guard let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as? WeatherDetailsViewController else { return }
//        var destinationDS = destinationVC.router!.dataStore!
//        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//        navigateToWeatherDetails(source: viewController!, destination: destinationVC)
//    }
//
//    //   MARK: Navigation
//
//    func navigateToWeatherDetails(source: WeatherDetailsViewController, destination: UIViewController) {
//        source.show(destination, sender: nil)
//    }
//
//    //   MARK: Passing data
//    func passDataToSomewhere(source: WeatherDetailsDataStore, destination: inout WeatherDetailsDataStore) {
//        destination.countryCoordinate = source.countryCoordinate
//    }
}
