//
//  CurrentWeatherRouter.swift
//  MirianMaglakelidze#28
//
//  Created by Admin on 8/31/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CurrentWeatherRoutingLogic {
    func routeToWeatherForecast()
}

protocol CurrentWeatherDataPassing {
    var dataStore: CurrentWeatherDataStore? { get }
}

final class CurrentWeatherRouter: NSObject, CurrentWeatherRoutingLogic, CurrentWeatherDataPassing {
    weak var viewController: CurrentWeatherViewController?
    var dataStore: CurrentWeatherDataStore?
    
    // MARK: Routing
    func routeToWeatherForecast() {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        guard let destinationVC = storyboard.instantiateViewController(withIdentifier: "WeatherDetailsViewController") as? WeatherDetailsViewController else { return }
        guard var destinationDS = destinationVC.router?.dataStore,
              let viewController = self.viewController,
              let dataStore = self.dataStore
        else { return }
        
        passDataToSomewhere(source: dataStore, destination: &destinationDS)
        navigateToWeatherDetails(source: viewController, destination: destinationVC)
    }
    
    //   MARK: Navigation
    
   private func navigateToWeatherDetails(source: CurrentWeatherViewController, destination: UIViewController) {
        source.show(destination, sender: nil)
    }
    
    //   MARK: Passing data
    private func passDataToSomewhere(source: CurrentWeatherDataStore, destination: inout WeatherDetailsDataStore) {
        destination.countryCoordinate = source.countryCoordinate
    }
    
}
