//
//  CountryRouter.swift
//  MirianMaglakelidze#28
//
//  Created by Admin on 8/30/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CountryRoutingLogic {
    func routeToWeather()
}

protocol CountryDataPassing {
    var dataStore: CountryDataStore? { get }
}

final class CountryRouter: NSObject, CountryRoutingLogic, CountryDataPassing {
    weak var viewController: CountryViewController?
    var dataStore: CountryDataStore?
    
    // MARK: Routing
    
    func routeToWeather() {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        guard let destinationVC = storyboard.instantiateViewController(withIdentifier: "CurrentWeatherViewController") as? CurrentWeatherViewController else { return }
        guard var destinationDS = destinationVC.router?.dataStore, let viewController = self.viewController else { return }
        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        navigateToWeather(source: viewController, destination: destinationVC)
    }
    
    // MARK: Navigation
    
   private func navigateToWeather(source: CountryViewController, destination: UIViewController) {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    private func passDataToSomewhere(source: CountryDataStore, destination: inout CurrentWeatherDataStore) {
        destination.countryCoordinate = source.countryCoordinate
    }
}
