//
//  CurrentWeatherWorker.swift
//  MirianMaglakelidze#28
//
//  Created by Admin on 8/31/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CurrentWeatherWorker {
    
    func createWeatherUrl(with baseUrl: String, lag: String, lat: String, key: String) -> URLRequest? {
        let urlsString = baseUrl
        guard var urlComponent = URLComponents(string: urlsString) else { return nil }
        urlComponent.queryItems =  [
            URLQueryItem(name: "lat", value: lat),
            URLQueryItem(name: "lon", value: lag),
            URLQueryItem(name: "appid", value: key)
        ]
        var urlRequest = URLRequest(url: (urlComponent.url!))
        urlRequest.httpMethod = "GET"
        return urlRequest
    }
}
