//
//  CurrentWeatherModels.swift
//  MirianMaglakelidze#28
//
//  Created by Admin on 8/31/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CurrentWeather {
  // MARK: Use cases

    enum GetWeather {
    struct Request {}
    
    struct Response {
        var weather: Weather?
    }
    
    struct ViewModel {
        let weather: WeatherViewModel
    }
  }
}
