//
//  CountryPresenter.swift
//  MirianMaglakelidze#28
//
//  Created by Admin on 8/30/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CountryPresentationLogic {
  func presentCountries(response: Country.GetCountry.Response)
}

class CountryPresenter: CountryPresentationLogic {
  weak var viewController: CountryDisplayLogic?
  
  // MARK: Do something
  
  func presentCountries(response: Country.GetCountry.Response) {
    let viewModel = Country.GetCountry.ViewModel(tableModel: response.countries)
    viewController?.displayCountries(viewModel: viewModel)
  }
}
